### ISSUE TITLE
[!] Invalid `Podfile` file: uninitialized constant Pod::Podfile::Flurry.

### ISSUE THREAD

**Issue by mcampsall** [xxsnakerxx/react-native-flurry-analytics#1]
Thanks for putting this together. I am having trouble installing it, having never used CocoaPods before.

My pod file looks like this:

    target 'myApp' do

      # Pods for myApp
      pod Flurry-iOS-SDK/FlurrySDK

      target 'myApp Tests' do
        inherit! :search_paths
        # Pods for testing
      end

    end

and I am getting the following error after trying `pod install` in the /ios dir of my project folder: 

    [!] Invalid `Podfile` file: uninitialized constant Pod::Podfile::Flurry.

Any ideas?

**Comment by xxsnakerxx** [comment]
@mcampsall Hi, I think you need just to wrap the pod name in single quotes
```bash 
# Pods for myApp
pod 'Flurry-iOS-SDK/FlurrySDK'
```

**Comment by mcampsall** [comment]
haha, that's it! Could you maybe update the read to include that? Anyone new to CocoaPods might benefit from it =)

Cheers.
