### ISSUE TITLE
Deprecations

### ISSUE THREAD

**Issue by njt1982** [xxsnakerxx/react-native-flurry-analytics#10]
![image](https://user-images.githubusercontent.com/384976/27833335-50b5b71a-60ca-11e7-8326-261cbd86d807.png)

setAppVersion
setDebugLogEnabled
setSessionContinueSeconds
setCrashReportingEnabled
setEventLoggingEnabled

All of these are flagged as deprecated.

Looks like we should be using FlurrySessionBuilder now?
http://flurry.github.io/flurry-ios-sdk/interface_flurry.html#afe1eee79e322f865073600a0aa13e008

**Comment by xxsnakerxx** [comment]
fixed in `2.1.0`
