### ISSUE TITLE
How to log a page view?

### ISSUE THREAD

**Issue by njt1982** [xxsnakerxx/react-native-flurry-analytics#11]
Using React Navigation, I have MANY scenes/pages in my app. How do I log page views?

There is a `logPageView` method here: http://flurry.github.io/flurry-ios-sdk/interface_flurry.html#a612da8f1557fa0e29d50640400d896ec

Does that method need exporting in https://github.com/xxsnakerxx/react-native-flurry-analytics/blob/master/ios/RNFlurryAnalytics.m?

**Comment by xxsnakerxx** [comment]
Hi, I will add this method when I fix deprecations (https://github.com/xxsnakerxx/react-native-flurry-analytics/issues/10)

I will try to do this ASAP

**Comment by xxsnakerxx** [comment]
Fixed in `2.1.0`

**Comment by njt1982** [comment]
thanks @xxsnakerxx - <24h turnaround time! Nice work :)
