### ISSUE TITLE
StackNavigator tracking

### ISSUE THREAD

**Issue by njt1982** [xxsnakerxx/react-native-flurry-analytics#12]
Is this the best way to track page views on a StackNavigator? This would be added as one of the navigator options alongside things like `gesturesEnabled`.

```
  onTransitionStart: (transitionProps) => {
    FlurryAnalytics.logEvent('PageLoad_' + transitionProps.scene.route.routeName, transitionProps.scene.route.params, false);
    FlurryAnalytics.logPageView();
  },
```

It seems PageView is just a "counter" without any context? And actual pages need to be tracked using events?

**Comment by xxsnakerxx** [comment]
Hi! I don't use this module now, so I don't know how `logPageView` works. 

When I used it, I tracked screen views with `logEvent('ViewPage', params)`

**Comment by xxsnakerxx** [comment]
Closed due no lack of feedback
