### ISSUE TITLE
com.flurry.android.FlurryAgent.builder cannot find symbol

### ISSUE THREAD

**Issue by AugustoAleGon** [xxsnakerxx/react-native-flurry-analytics#18]
Hello,

I currently have a problem with the FlurryAgent library which the constructor method is not defined. 

This is the log:

`:react-native-flurry-analytics:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
C:\react-hermione\node_modules\react-native-flurry-analytics\android\src\main\java\com\xxsnakerxx\flurryanalytics\FlurryAnalyticsModule.java:16: error: cannot find symbol
import com.flurry.android.FlurryAgent.Builder;
                                     ^
  symbol:   class Builder
  location: class FlurryAgent
C:\react-hermione\node_modules\react-native-flurry-analytics\android\src\main\java\com\xxsnakerxx\flurryanalytics\FlurryAnalyticsModule.java:23: error: cannot find symbol
  private Builder mFlurryAgentBuilder = null;
          ^
  symbol:   class Builder
  location: class FlurryAnalyticsModule
C:\react-hermione\node_modules\react-native-flurry-analytics\android\src\main\java\com\xxsnakerxx\flurryanalytics\FlurryAnalyticsModule.java:33: error: cannot find symbol
    mFlurryAgentBuilder = new FlurryAgent.Builder();
                                         ^
  symbol:   class Builder
  location: class FlurryAgent
3 errors
:react-native-flurry-analytics:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-flurry-analytics:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.`

I am checking the file of FlurryAnalyticsModule.java but there is any builder of that package.
Let me know if someone can help me.
In advance thank you.

**Comment by Alevs2R** [comment]
the same problem

**Comment by aiossa** [comment]
the same here

**Comment by flok10** [comment]
Same here

**Comment by ddolheguy** [comment]
Did some investigation and found the issue is in relation to the flurry package in the build.gralde file.

Change the following and it will work:
FROM:  compile 'com.flurry.android:analytics:++@aar'
TO:   compile 'com.flurry.android:analytics:7.0.0@aar'

Really, this should be locked to a version otherwise this library might fail like it is now.

**Comment by AugustoAleGon** [comment]
Tested and it works. Probably should be something that is required for now.
