### ISSUE TITLE
Android devices showing up as iPhone platform

### ISSUE THREAD

**Issue by CyrusDG** [xxsnakerxx/react-native-flurry-analytics#2]
Is it possible to report events on Android to the Android platform in Flurry?  Right now, all events, including Android, are showing up under the iPhone platform. I'm guessing it is because our API key is from the iPhone SDK. Is it possible to have them separate using this react native package?

**Comment by xxsnakerxx** [comment]
@CyrusDG you need to register android app in flurry, then you can do smth like this

```javascript
import {
  Platform,
} from 'react-native';

const flurryApiKey = {
  ios: 'ios_key_here',
  android: 'android_key_here',
}

// somewhere in your app
FlurryAnalytics.startSession(flurryApiKey[Platform.OS]);
```

**Comment by CyrusDG** [comment]
Perfect -- thanks for the quickly reply!
