### ISSUE TITLE
Argument List Too Long

### ISSUE THREAD

**Issue by njt1982** [xxsnakerxx/react-native-flurry-analytics#21]
All was compiling fine and suddenly getting this error cause by (I *think* this line)...

https://github.com/xxsnakerxx/react-native-flurry-analytics/blob/d2d03e9a6aa934f232ee9339b74ebc6bf63a9a7d/ios/RNFlurryAnalytics.xcodeproj/project.pbxproj#L204

```

Showing All Issues
Argument list too long: recursive header expansion failed at /Users/nthompson/Documents/react-native/*****App/node_modules/react-native-flurry-analytics/ios/../../../ios/build/Index/DataStore/v5/records/DV.
```

Folder seems ok to me?!
```
$ ls -1 /Users/nthompson/Documents/react-native/IndexServicesApp/ios/build/Index/DataStore/v5/records/DV/
JSCPerfStats.cpp-23M32VXI4Q1DV
RCTMaskedViewManager.m-9UZTR4K6RJDV
Swift.swiftmodule_String-2WISYUSBPY6DV
UIFocusSystem.h-ZDCGEK602IDV
_u_int.h-1MI99WHXFA2DV
```

So my questions are:
1) Why do we need to add the entire ios folder as a recursive search path for the react-native-flurry plugin...
2) Any idea's why this error would crop up unexpectedly? I've made no project file changes or anything...

Seems to be a common error in many RN plugins.

**Comment by njt1982** [comment]
I've made the error go away by changing the Framework Search Paths and the Header Search Paths to:
```
$(PROJECT_DIR)/../../../ios/Pods/Flurry-iOS-SDK/**
```
(ie I added `Pods/Flurry-iOS-SDK/` before the `**`)

I'm now getting the same problem with https://github.com/devfd/react-native-google-signin

**Comment by njt1982** [comment]
I've opened PR #22 to fix this... Any chance of a review/test/merge, please @xxsnakerxx ?

**Comment by xxsnakerxx** [comment]
@njt1982 Merged! Thanks! 👍🏻

**Comment by njt1982** [comment]
w00t! Now just for @devfd to merge the same fix for Google Sign In ;) https://github.com/devfd/react-native-google-signin/pull/333
