### ISSUE TITLE
crash on backbutton [ANDROID]

### ISSUE THREAD

**Issue by proProbe** [xxsnakerxx/react-native-flurry-analytics#4]
Hi!

Thanks a lot for the library. It works quite well. Ive picked on an error that occurs when exiting the app with `androidBackButton` and then start the app again. I then get the error:
`console.error: "FurryAnalytics.setAppVersion: method must be called prior to invoking "startSession"`.

My current code implementing this is:
```
FlurryAnalytics.setAppVersion('1.1');
FlurryAnalytics.setEventLoggingEnabled(true);
FlurryAnalytics.setDebugLogEnabled(true);
FlurryAnalytics.setCrashReportingEnabled(true);
FlurryAnalytics.startSession(key);
```

**Comment by proProbe** [comment]
Looking at it further, it seems like exiting the app through backbutton on android to then open the app again `Remounts` the app triggering the `startSession` again. I got the following error when opening the app again after exit `FlurryAnalytics.startSession: already called` which would indicate this. any ideas how to avoid this?

**Comment by panuta** [comment]
I'm having this issue too. @proProbe @xxsnakerxx 

Did you come to any solution?

**Comment by proProbe** [comment]
@panuta I realized that it might not have anything to do with FlurryAnalytics. Probably, the service tries to start again which the phone doesnt really like. You probably need to configure so the scenes in your app initiates it at a appropriate stage in your app
