### ISSUE TITLE
1.1.0 broke my project because of 0.40 support

### ISSUE THREAD

**Issue by carleryd** [xxsnakerxx/react-native-flurry-analytics#7]
Just wanted to inform that the latest bump to 1.1.0 broke my project because I had "^1.0.3" in my package.json and was using react-native < 0.40.
I resolved the issue by setting "1.0.3".

Should this not have been a Major version bump rather than a Minor one?

**Comment by xxsnakerxx** [comment]
I agree, published `2.0`, thanks
